name: delivery
description: "Aplicativo de entregas."
publish_to: 'none' 

version: 0.6.03+25

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  http: ^1.2.2
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  mobx_codegen: ^2.6.1
  get_it: ^8.0.0
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.1.0
  material_symbols_icons: ^4.2785.1
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  geocoding: ^3.0.0
  geoflutterfire2: ^2.3.15
  mobile_scanner: ^5.2.3
  firebase_auth: ^4.16.0
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_remote_config: ^4.4.7
  cloud_functions: ^4.7.6
  google_maps_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
