name: delivery
description: "Aplicativo de entregas."
publish_to: 'none' 

version: 0.1.0+5

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  http: ^1.2.2
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  build_runner: ^2.4.12
  mobx_codegen: ^2.6.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_dynamic_links: ^5.4.8
  get_it: ^7.7.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # - .env
    - assets/images/
