// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOa3di-OtfcDMBp3Y0RdpUYs2NWikp-GE',
    appId: '1:235384305125:web:18b76c93f227abc5492b0c',
    messagingSenderId: '235384305125',
    projectId: 'delivery-16712',
    authDomain: 'delivery-16712.firebaseapp.com',
    storageBucket: 'delivery-16712.appspot.com',
    measurementId: 'G-2RL3BKQJ9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwgLCIfeeFYHJobozqLAl7K8UIcN4LWbY',
    appId: '1:235384305125:android:2dc58ad897e2e205492b0c',
    messagingSenderId: '235384305125',
    projectId: 'delivery-16712',
    storageBucket: 'delivery-16712.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB45cs_MfEGZvjKokb1s3rFuDWe3YB6_ac',
    appId: '1:235384305125:ios:4057b0827b43b43e492b0c',
    messagingSenderId: '235384305125',
    projectId: 'delivery-16712',
    storageBucket: 'delivery-16712.appspot.com',
    iosBundleId: 'br.dev.rralves.delivery',
  );
}
